module.exports = {
  client: require("./src/client"),
  createClass: require("./src/createClass"),
  createDatabase: require("./src/createDatabase"),
  createIdIndex: require("./src/createIdIndex"),
  createIndex: require("./src/createIndex"),
  createInstance: require("./src/createInstance"),
  createKey: require("./src/createKey"),
  createToken: require("./src/createToken"),
  deleteId: require("./src/deleteId"),
  deleteName: require("./src/deleteName"),
  deleteInstance: require("./src/deleteInstance"),
  getId: require("./src/getId"),
  getName: require("./src/getName"),
  getInstance: require("./src/getInstance"),
  getInstances: require("./src/getInstances"),
  match: require("./src/match"),
  replaceInstance: require("./src/replaceInstance"),
  setId: require("./src/setId"),
  setName: require("./src/setName"),
  updateId: require("./src/updateId"),
  updateInstance: require("./src/updateInstance")
};
